Fix site creation for maven plugins
eclipse-cbi/org.eclipse.cbi pull request #323
Opened 2023-08-09 12:43 UTC by fredg02

- change parent pom of Maven plugins to `maven-plugin-parent`
- change parent pom of  `maven-plugin-parent` to `cbi-build-parent`
- fix URL to Eclipse Foundation logo in site.xml
- the site can be generated by doing the following:
  1. Run `mvn clean install -DskipTests` in root dir
  2. Run `mvn clean verify site -DskipTests` in maven-plugins dir
  3. Run `mvn site:stage` in maven-plugins dir
  4. Site can be found at maven-plugins/target/staging/cbi-build-parent/maven-plugin-parent/index.html

2023-08-09 13:14 UTC, mbarbero requested changes
by doing that, you won't benefit from the setup in cbi-build-parent

2023-08-09 13:24 UTC, fredg02 commented
> by doing that, you won't benefit from the setup in cbi-build-parent

Why not? 
E.g. for `eclipse-winsigner-plugin` the parent pom hierarchy is changing from
`eclipse-winsigner-plugin` -> `cbi-build-parent` to \
`eclipse-winsigner-plugin` -> `maven-plugin-parent` -> `cbi-build-parent` \
so it should still inherit everything from the `cbi-build-parent` parent pom.

2023-08-11 17:20 UTC, mbarbero commented
uhm, I've mixed feeling about mixing up the hierarchy, but if it does not break anything, go for it (multimodules site generation is a mess)

2023-08-16 10:52 UTC, fredg02 commented
I've compared the console log output of `mvn clean verify -DskipTests` for the `main` and `fix_site_creation` branches and found no noticeable difference.
If something breaks, I will roll back the commit.

2023-08-16 10:53 UTC, merged